### PR TITLE
Jwt

### PR DESCRIPTION
**Pull request by nbur4556**
To test, pull and checkout to this branch and create an env.json file in the root directory.

{
    "JWT_SECRET": {MAKE UP A PASSWORD HERE}
}

DO NOT push the env.json to Github. This branch should have the file git ignored, but if you checkout to another branch make sure to remove the env.json file.

### CODE REVIEW

**Comment by tylerdrewwork** [comment]
Is there any way I can test this without the API Routes? I'm trying to finish them up right now so we can seem them work together in action.

**Comment by nbur4556** [comment]
> Is there any way I can test this without the API Routes? I'm trying to finish them up right now so we can seem them work together in action.

Didn't think of that... When I was working on it I had just written some testing functions, on the controller files and ran it using node. I deleted those testing functions though, but you could probably find them in the previous commits using git graph

**Review by smundhada — APPROVED** [review]
Approved!

**Review by tylerdrewwork — APPROVED** [review]
tested, works perfectly. great job!!

**Pull request merged**
