### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by nbur4556**

### CODE REVIEW

**Review by tylerdrewwork — COMMENTED** [review]
Looks really great! Does the screenshot path need to be updated?

**Comment by nbur4556** [comment]
Yes screenshot does need to be updated but I wanted to edit that after the site was styled. What do you think?

**Comment by nbur4556** [comment]
Also is MIT license ok?

**Review by tylerdrewwork — APPROVED** [review]
yeah, that sounds good!

**Pull request merged**
